sudo: required
services:
    - docker
    
before_install:
  - docker build -t unaldeniz/docker-react -f Dockerfile.dev .

script: 
 - docker run -e CI=true unaldeniz/docker-react npm run test

language: generic